### ISSUE TITLE
Diaglog Width not working

### ISSUE THREAD

**Issue by briceamk** [ankit1329/ngx-mat-alert-confirm#2]
Hello,
First I want to say thanks a lot for this module.
I have some probleme. this is my config:

`const okButton: ConfirmButtonConfig = {
  id: '1',
  text: 'OK',
  color: 'primary',
  type: 'fab',
  icon: 'check'
}

const cancelButton: ConfirmButtonConfig = {
  id: '0',
  text: 'CANCEL',
  color: 'warn', // 'primary' | 'accent' | 'warn'
  type: 'fab',  //'basic' | 'raised' | 'stroked' | 'flat' | 'icon' | 'fab' | 'minifab'
  icon: 'clear'
}

const buttonArr: Array < ConfirmButtonConfig > = [okButton, cancelButton];

export let confirmConfig: ConfirmConfig = {
  title: 'Etes vous sûre?',
  titleSize: 28,
  message: 'This action cannot be reversed!',
  messageSize: 16,
  matIcon: 'access_alarm',
  iconAnimation: 'fadeOut',
  iconColor: 'primary',
  buttons: [buttonArr],
  disableClose: true, // true | false
  autoFocus: true, // true | false
  restoreFocus: true,
  width: undefined
};`

but dialog **width** not working well.

![image](https://user-images.githubusercontent.com/12937130/99191137-fbd52a80-276a-11eb-93f6-eea295a436fe.png)

I am using angular 10 and angular material 10

**Comment by ankit1329** [comment]
Hello @briceamk 
I don't see any specific reason for this icon to misalign. But I do see something which might cause issues.
Try removing the 'buttons' property from config as shown below and assign separately.

```export let confirmConfig: ConfirmConfig = {
title: 'Etes vous sûre?',
titleSize: 28,
message: 'This action cannot be reversed!',
messageSize: 16,
matIcon: 'access_alarm',
iconAnimation: 'fadeOut',
iconColor: 'primary',
buttons: [buttonArr], <---------- remove this
disableClose: true, // true | false
autoFocus: true, // true | false
restoreFocus: true,
width: undefined
};
```

Assign as follows anywhere but before opening the confirm box:
`this.confirmConfig.buttons = buttonArr;`

If this doesn't work then its probably a browser or screen resolution thing (may differ on laptop, tablet and mobile screens). 
If you could open a plunker where the bug is reproduced, I can look into it otherwise let me know your browser and screen, I'll test it and get back to you.

**Comment by briceamk** [comment]
> Hello @briceamk
> I don't see any specific reason for this icon to misalign. But I do see something which might cause issues.
> Try removing the 'buttons' property from config as shown below and assign separately.
> 
> ```
> title: 'Etes vous sûre?',
> titleSize: 28,
> message: 'This action cannot be reversed!',
> messageSize: 16,
> matIcon: 'access_alarm',
> iconAnimation: 'fadeOut',
> iconColor: 'primary',
> buttons: [buttonArr], <---------- remove this
> disableClose: true, // true | false
> autoFocus: true, // true | false
> restoreFocus: true,
> width: undefined
> };
> ```
> 
> Assign as follows anywhere but before opening the confirm box:
> `this.confirmConfig.buttons = buttonArr;`
> 
> If this doesn't work then its probably a browser or screen resolution thing (may differ on laptop, tablet and mobile screens).
> If you could open a plunker where the bug is reproduced, I can look into it otherwise let me know your browser and screen, I'll test it and get back to you.

Hello @ankit1329,
I have tried, but it still not working. in your website demo working perfectly on my laptop.

**Comment by ankit1329** [comment]
@briceamk 
This might be a css issue then. You can check if anywhere in your app you are altering the css of `<mat-icon>` element directly.
I would really like to see code where this issue is reproduced, maybe if u could open a plunker or even send me a sample code where this issue is present over email, i'll be very happy to take a look and fix this for you.

**Comment by briceamk** [comment]
@ankit1329 
I think you a right. Since the beguining of my current project i have a problem with margin of `<mat-icon>`. To check if is that the issue I have create a new project and everything work perfectly. I will check later where I altered the `<mat-icon>` margin in my project.
Thanks for responding me quickly.
